// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Category struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type CreateCategoryInput struct {
	Name string `json:"name"`
}

type CreateLinkInput struct {
	WishlistItemID string  `json:"wishlistItemId"`
	URL            string  `json:"url"`
	Title          *string `json:"title,omitempty"`
	Price          *string `json:"price,omitempty"`
}

type CreateUserInput struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

type CreateWishlistInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	CategoryID  *string `json:"categoryId,omitempty"`
}

type CreateWishlistItemInput struct {
	WishlistID  string  `json:"wishlistId"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	CategoryID  *string `json:"categoryId,omitempty"`
	Rating      *int    `json:"rating,omitempty"`
}

type Link struct {
	ID        string  `json:"id"`
	URL       string  `json:"url"`
	Title     *string `json:"title,omitempty"`
	Price     *string `json:"price,omitempty"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}

type Mutation struct {
}

type MutationResponse struct {
	Success bool    `json:"success"`
	Message *string `json:"message,omitempty"`
}

type Query struct {
}

type UpdateLinkInput struct {
	URL   string  `json:"url"`
	Title *string `json:"title,omitempty"`
	Price *string `json:"price,omitempty"`
}

type UpdateWishlistItemInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	CategoryID  *string `json:"categoryId,omitempty"`
	Rating      *int    `json:"rating,omitempty"`
}

type User struct {
	ID        string  `json:"id"`
	Email     string  `json:"email"`
	Name      string  `json:"name"`
	AvatarURL *string `json:"avatarUrl,omitempty"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}

type Wishlist struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Description *string         `json:"description,omitempty"`
	Category    *Category       `json:"category,omitempty"`
	Owner       *User           `json:"owner"`
	Items       []*WishlistItem `json:"items"`
	CreatedAt   string          `json:"createdAt"`
	UpdatedAt   string          `json:"updatedAt"`
}

type WishlistItem struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description,omitempty"`
	Category    *Category `json:"category,omitempty"`
	Rating      *int      `json:"rating,omitempty"`
	Links       []*Link   `json:"links"`
	CreatedAt   string    `json:"createdAt"`
	UpdatedAt   string    `json:"updatedAt"`
}
