package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"
	"strconv"

	"github.com/cesaraugstz/comrade-notes/api/internal/database"
)

// CreateWishlist is the resolver for the createWishlist field.
func (r *mutationResolver) CreateWishlist(ctx context.Context, input CreateWishlistInput) (*MutationResponse, error) {
	userID := getUserIDFromContext(ctx)
	if userID == 0 {
		return &MutationResponse{Success: false, Message: stringPtr("unauthorized")}, nil
	}

	var categoryID *uint
	if input.CategoryID != nil {
		id, err := strconv.ParseUint(*input.CategoryID, 10, 32)
		if err != nil {
			return &MutationResponse{Success: false, Message: stringPtr("invalid category ID")}, nil
		}
		categoryID = uintPtr(uint(id))
	}

	wishlist := &database.Wishlist{
		Name:        input.Name,
		Description: stringValue(input.Description),
		CategoryID:  categoryID,
		OwnerID:     userID,
	}

	if err := r.DB.WithContext(ctx).Create(wishlist).Error; err != nil {
		return &MutationResponse{Success: false, Message: stringPtr("failed to create wishlist")}, nil
	}

	return &MutationResponse{Success: true}, nil
}

// CreateWishlistItem is the resolver for the createWishlistItem field.
func (r *mutationResolver) CreateWishlistItem(ctx context.Context, input CreateWishlistItemInput) (*MutationResponse, error) {
	wishlistID, err := strconv.ParseUint(input.WishlistID, 10, 32)
	if err != nil {
		return &MutationResponse{Success: false, Message: stringPtr("invalid wishlist ID")}, nil
	}

	var categoryID *uint
	if input.CategoryID != nil {
		id, err := strconv.ParseUint(*input.CategoryID, 10, 32)
		if err != nil {
			return &MutationResponse{Success: false, Message: stringPtr("invalid category ID")}, nil
		}
		categoryID = uintPtr(uint(id))
	}

	item := &database.WishlistItem{
		Name:        input.Name,
		Description: stringValue(input.Description),
		CategoryID:  categoryID,
		Rating:      input.Rating,
		WishlistID:  uint(wishlistID),
	}

	if err := r.DB.WithContext(ctx).Create(item).Error; err != nil {
		return &MutationResponse{Success: false, Message: stringPtr("failed to create item")}, nil
	}

	return &MutationResponse{Success: true}, nil
}

// CreateLink is the resolver for the createLink field.
func (r *mutationResolver) CreateLink(ctx context.Context, input CreateLinkInput) (*MutationResponse, error) {
	itemID, err := strconv.ParseUint(input.WishlistItemID, 10, 32)
	if err != nil {
		return &MutationResponse{Success: false, Message: stringPtr("invalid item ID")}, nil
	}

	link := &database.Link{
		URL:            input.URL,
		Title:          stringValue(input.Title),
		Price:          input.Price,
		WishlistItemID: uint(itemID),
	}

	if err := r.DB.WithContext(ctx).Create(link).Error; err != nil {
		return &MutationResponse{Success: false, Message: stringPtr("failed to create link")}, nil
	}

	return &MutationResponse{Success: true}, nil
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input CreateCategoryInput) (*MutationResponse, error) {
	category := &database.Category{Name: input.Name}

	if err := r.DB.WithContext(ctx).Create(category).Error; err != nil {
		return &MutationResponse{Success: false, Message: stringPtr("failed to create category")}, nil
	}

	return &MutationResponse{Success: true}, nil
}

// Wishlists is the resolver for the wishlists field.
func (r *queryResolver) Wishlists(ctx context.Context) ([]*Wishlist, error) {
	userID := getUserIDFromContext(ctx)
	if userID == 0 {
		return nil, nil
	}

	var dbWishlists []database.Wishlist
	err := r.DB.WithContext(ctx).
		Preload("Category").
		Preload("Owner").
		Preload("Items.Category").
		Preload("Items.Links").
		Where("owner_id = ?", userID).
		Find(&dbWishlists).Error

	if err != nil {
		return nil, err
	}

	return convertWishlists(dbWishlists), nil
}

// Wishlist is the resolver for the wishlist field.
func (r *queryResolver) Wishlist(ctx context.Context, id string) (*Wishlist, error) {
	wishlistID, err := strconv.ParseUint(id, 10, 32)
	if err != nil {
		return nil, err
	}

	var dbWishlist database.Wishlist
	err = r.DB.WithContext(ctx).
		Preload("Category").
		Preload("Owner").
		Preload("Items.Category").
		Preload("Items.Links").
		First(&dbWishlist, wishlistID).Error

	if err != nil {
		return nil, err
	}

	return convertWishlist(&dbWishlist), nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*Category, error) {
	var dbCategories []database.Category
	err := r.DB.WithContext(ctx).Find(&dbCategories).Error
	if err != nil {
		return nil, err
	}

	return convertCategories(dbCategories), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
